import React from 'react'

const about = () => {
  return (
    <div>This is about</div>
  )
}

export default about

export const metadata = {
  title: "Facebook About",
  description: "Generated by create next app",
};